#!/usr/bin/env php
<?php

declare(strict_types=1);

$scriptDir = __DIR__;
$skillDir = dirname($scriptDir);
$packageRoot = dirname($scriptDir, 5);
$outputPath = $skillDir.'/references/api-index.generated.md';
$checkOnly = in_array('--check', $argv, true);

$relativeFiles = [
    'src/Krud.php',
    'src/KituKizuri.php',
    'src/App/Traits/Krud/QueryBuilderTrait.php',
    'src/App/Traits/Krud/UiTrait.php',
    'src/App/Traits/Krud/FieldTrait.php',
    'src/App/Traits/Krud/TableTrait.php',
    'src/App/Traits/Krud/ChartTrait.php',
    'src/App/Traits/Krud/HelpTrait.php',
    'src/App/Traits/Krud/PermissionTrait.php',
];

/**
 * @return array<int, array<string, mixed>>
 */
function parseMethods(string $absolutePath, string $relativePath): array
{
    $lines = file($absolutePath, FILE_IGNORE_NEW_LINES);
    if ($lines === false) {
        throw new RuntimeException("Unable to read {$absolutePath}");
    }

    $type = basename($relativePath, '.php');
    $methods = [];
    $docBuffer = [];
    $insideDoc = false;

    foreach ($lines as $index => $line) {
        $lineNumber = $index + 1;
        $trimmed = trim($line);

        if (str_starts_with($trimmed, '/**')) {
            $insideDoc = true;
            $docBuffer = [$trimmed];
        } elseif ($insideDoc) {
            $docBuffer[] = $trimmed;
            if (str_contains($trimmed, '*/')) {
                $insideDoc = false;
            }
        }

        if (!preg_match(
            '/^\s*(public|protected|private)\s+(static\s+)?function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\((.*)\)\s*(?::\s*([^\{]+))?/',
            $line,
            $matches
        )) {
            continue;
        }

        $summary = '';
        foreach ($docBuffer as $docLine) {
            $clean = trim($docLine, " \t\n\r\0\x0B/*");
            if ($clean === '' || str_starts_with($clean, '@') || $clean === $matches[3]) {
                continue;
            }
            $summary = $clean;
            break;
        }

        $signature = trim($matches[1].' '.($matches[2] ?? '').'function '.$matches[3].'('.$matches[4].')');
        if (!empty($matches[5])) {
            $signature .= ': '.trim($matches[5]);
        }

        $methods[] = [
            'type' => $type,
            'visibility' => $matches[1],
            'static' => trim((string) ($matches[2] ?? '')) === 'static',
            'name' => $matches[3],
            'signature' => $signature,
            'file' => $relativePath,
            'line' => $lineNumber,
            'summary' => $summary,
        ];

        $docBuffer = [];
    }

    return $methods;
}

$allMethods = [];
foreach ($relativeFiles as $relativeFile) {
    $absolutePath = $packageRoot.'/'.$relativeFile;
    if (!is_file($absolutePath)) {
        throw new RuntimeException("Expected source file not found: {$relativeFile}");
    }
    $allMethods = array_merge($allMethods, parseMethods($absolutePath, $relativeFile));
}

$groups = [];
foreach ($allMethods as $method) {
    $groups[$method['file']][] = $method;
}

$lines = [
    '# Generated API inventory',
    '',
    'Generated from the current package source by `scripts/generate-api-index.php`.',
    'Do not edit this file manually.',
    '',
    'Total methods found: **'.count($allMethods).'**.',
    '',
];

foreach ($groups as $file => $methods) {
    $lines[] = '## `'.$file.'`';
    $lines[] = '';
    $lines[] = '| Visibility | Method | Signature | Source | Summary |';
    $lines[] = '|---|---|---|---|---|';

    foreach ($methods as $method) {
        $summary = str_replace('|', '\\|', $method['summary']);
        $signature = str_replace('|', '\\|', $method['signature']);
        $lines[] = sprintf(
            '| `%s%s` | `%s` | `%s` | `%s:%d` | %s |',
            $method['visibility'],
            $method['static'] ? ' static' : '',
            $method['name'],
            $signature,
            $method['file'],
            $method['line'],
            $summary
        );
    }

    $lines[] = '';
}

$content = implode(PHP_EOL, $lines).PHP_EOL;

if ($checkOnly) {
    if (!is_file($outputPath)) {
        fwrite(STDERR, "Generated inventory is missing: {$outputPath}\n");
        exit(1);
    }

    $existing = file_get_contents($outputPath);
    if ($existing !== $content) {
        fwrite(STDERR, "API inventory is stale. Run:\nphp {$scriptDir}/generate-api-index.php\n");
        exit(1);
    }

    fwrite(STDOUT, "API inventory is current.\n");
    exit(0);
}

if (file_put_contents($outputPath, $content) === false) {
    throw new RuntimeException("Unable to write {$outputPath}");
}

fwrite(STDOUT, "Wrote {$outputPath} with ".count($allMethods)." methods.\n");
